name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: s1.ct8.pl
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_nodejs/

      - name: Build and run
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd domains/${{ secrets.CT8_DOMAIN }}/public_nodejs/
            npm ci
            npm run build
            devil www restart ${{ secrets.CT8_DOMAIN }}
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD}}
          args: "-tt"
